<!-- Travis badge -->
<img src="https://travis-ci.org/ice-services/moleculer.svg?branch=master" />

<!-- Coveralls badge -->
<img src="https://coveralls.io/repos/github/ice-services/moleculer/badge.svg?branch=master" />

<!-- Codacy badge -->
<img src="https://api.codacy.com/project/badge/Grade/b108c12cbf554fca9c66dd1925d11cd0" />

<!-- Code Climate badge -->
<img src="https://codeclimate.com/github/ice-services/moleculer/badges/gpa.svg" />

<!-- Snyk badge -->
<img src="https://snyk.io/test/github/ice-services/moleculer/badge.svg" />

<!-- NPM downloads -->
<img src="https://img.shields.io/npm/dm/moleculer.svg" />
