<!-- NPM version badge -->
<img src="https://badgen.net/npm/v/moleculer" />

<!-- Travis badge -->
<img src="https://travis-ci.org/moleculerjs/moleculer.svg?branch=master" />

<!-- Coveralls badge -->
<img src="https://coveralls.io/repos/github/moleculerjs/moleculer/badge.svg?branch=master" />

<!-- Codacy badge -->
<img src="https://api.codacy.com/project/badge/Grade/ec4dab24e4ea4c1eb0d1590f12c81a46" />

<!-- Code Climate badge -->
<img src="https://api.codeclimate.com/v1/badges/05ef990fe1ccb3e56067/maintainability" />

<!-- Snyk badge -->
<img src="https://snyk.io/test/github/moleculerjs/moleculer/badge.svg" />

<!-- NPM downloads -->
<a href="http://www.npmtrends.com/moleculer" target="_blank">
    <img src="https://img.shields.io/npm/dm/moleculer.svg" />
</a>
