<section>
	<h2 class="section-title">Who is using Moleculer?</h2>
	<div class="company-list">
		<a href="https://www.conciergeauctions.com/" class="company-logo" target="_blank">
			<img src="https://s3.amazonaws.com/media.conciergeauctions.com/logo.jpg" alt="Concierge Auctions" />
		</a>
		<a href="http://www.ingsw.com/" class="company-logo" target="_blank">
			<img src="https://user-images.githubusercontent.com/306521/31340277-edc01780-ad05-11e7-952e-0c959a107a2c.png" alt="ingenious" />
		</a>
		<a href="https://www.thb.co.in/" class="company-logo" target="_blank">
			<img src="https://thehealthybillion.com/images/thb/landingpage/logobig.png" alt="THB" />
		</a>
	</div>
	<div class="company-list">
		<a href="https://zaoblako.ru/" class="company-logo" target="_blank">
			<img src="https://zaoblako.ru/images/zaoblako_l.png" alt="Zaoblako" />
		</a>
		<a href="http://altcoinminingpools.com" class="company-logo" target="_blank">
			<img src="http://altcoinminingpools.com/assets/img/altcoinminingpools.png" alt="Altcoin mining pools" />
		</a>
	</div>
	<div class="company-missing">If you don't see here your company, <a href="https://github.com/moleculerjs/moleculer/issues/101" target="_blank">tell us.</a></div>
</section>
