<!-- Patreon link -->
<a href="https://www.patreon.com/moleculer" target="_blank"><img src="/images/patreon.svg" alt="Patreon support" /></a>
<!-- Paypal.me link -->
<a href="https://paypal.me/meregnorbert/50usd" target="_blank"><img src="/images/paypal_donate.svg" alt="Paypal donate" /></a>
<!-- GitHub Sposor link -->
<a class="github-button" href="https://github.com/sponsors/moleculerjs" data-icon="octicon-heart" aria-label="Sponsor @moleculerjs on GitHub">Sponsor</a>
<script async defer src="https://buttons.github.io/buttons.js"></script>
