<!-- GitHub Star -->
<a class="github-button" href="https://github.com/ice-services/moleculer" data-count-href="/ice-services/moleculer" data-show-count="true" data-count-aria-label="# stargazers on GitHub" aria-label="Star ice-services/moleculer on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/ice-services/moleculer/fork" data-count-href="/ice-services/moleculer/fork" data-show-count="true" data-count-aria-label="# forks on GitHub" aria-label="Fork ice-services/moleculer on GitHub">Fork</a>
<!-- Tweet button -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://moleculer-services/" data-text="Moleculer - A fast & powerful microservices framework for Node.js" data-hashtags="moleculer,microservices,nodejs">Tweet</a>
<!-- Twitter follow button -->
<a href="https://twitter.com/MoleculerJS" class="twitter-follow-button" data-show-count="false">Follow @MoleculerJS</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>
